version: "3.3"

services:
  sp00:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: sp00
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=password
    ports:
      - "8000:8000"

  sp01:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: sp01
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_APPS_URL=/var/tmp/IIJFXZ.tar.gz
      - SPLUNK_PASSWORD=password
    ports:
      - "8081:8000"
    volumes:
      - /var/tmp/IIJFXZ.tar.gz:/var/tmp/IIJFXZ.tar.gz

  sp02:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: sp02
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_APPS_URL=/var/tmp/IIJFXZ.tar.gz
      - SPLUNK_PASSWORD=password
    ports:
      - "8082:8000"
    volumes:
      - /var/tmp/IIJFXZ.tar.gz:/var/tmp/IIJFXZ.tar.gz

  sp03:
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: sp03
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_APPS_URL=/var/tmp/IIJFXZ.tar.gz
      - SPLUNK_PASSWORD=password
    ports:
      - "8083:8000"
    volumes:
      - /var/tmp/IIJFXZ.tar.gz:/var/tmp/IIJFXZ.tar.gz
