FROM nginx:1.13-alpine
COPY default.conf /etc/nginx/conf.d/default.conf
COPY ssl.conf /etc/nginx/conf.d/ssl.conf
COPY nonssl.conf /etc/nginx/conf.d/nonssl.conf
COPY server.crt /etc/nginx/server.crt
COPY server.key /etc/nginx/server.key
