FROM nginx:1.17-alpine
MAINTAINER EndlessPancake <endless.pancake4u@gmail.com>
COPY default.conf /etc/nginx/conf.d/default.conf
COPY server.crt /etc/nginx/server.crt
COPY server.key /etc/nginx/server.key

# ENV
WORKDIR /etc/nginx 
